const types = {
	REQUEST_SERVICES: 'REQUEST_SERVICES',
	REQUEST_SUCCESS_SERVICES: 'REQUEST_SUCCESS_SERVICES',
	REQUEST_FAILURE_SERVICES: 'REQUEST_FAILURE_SERVICES',
	REQUEST_SERVICE: 'REQUEST_SERVICE',
	REQUEST_SERVICE_SUCCESS: 'REQUEST_SERVICE_SUCCESS',
	REQUEST_MY_SERVICES: 'REQUEST_MY_SERVICES',
	REQUEST_MY_SERVICES_SUCCESS: 'REQUEST_MY_SERVICES_SUCCESS',
	DELETE_SERVICE: 'DELETE_SERVICE',
	CREATE_SERVICE: 'CREATE_SERVICE',
	CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
	UPDATE_SERVICE: 'UPDATE_SERVICE',
	UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
};

export default types;
