const types = {
	REQUEST_SERVICES: 'REQUEST_SERVICES',
	REQUEST_SUCCESS_SERVICES: 'REQUEST_SUCCESS_SERVICES',
	REQUEST_FAILURE_SERVICES: 'REQUEST_FAILURE_SERVICES',
	DELETE_SERVICE: 'DELETE_SERVICE',
};

export default types;
