const types = {
	REQUEST_SERVICES: 'REQUEST_SERVICES',
	REQUEST_SUCCESS_SERVICES: 'REQUEST_SUCCESS_SERVICES',
	REQUEST_FAILURE_SERVICES: 'REQUEST_FAILURE_SERVICES',
	DELETE_SERVICE: 'DELETE_SERVICE',
	CREATE_SERVICE: 'CREATE_SERVICE',
	CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
	UPDATE_SERVICE: 'UPDATE_SERVICE',
};

export default types;
